<?php
@session_start();
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/assets/css/output.css">
    <script src="/assets/js/tailwind.js"></script>
    <title>Vision Chat | Connexion</title>
</head>

<body>
    <div class="lg:max-w-[70%] lg:mt-[140px] lg:h-[400px] m-auto shadow-2xl flex lg:justify-between bg-[url('/assets/stories/bg.jpg')] rounded">
        <div>Vision Chat</div>
        <div
            class="lg:basis-[45%] bg-gradient-to-b from-green-300 to-green-600 lg:rounded-l-full lg:border-t-[1px] lg:border-b-[1px] lg:border-[#eee]">
            <div class="lg:mt-[42px] lg:mr-[10px] lg:max-w-[70%] m-auto p-1 flex flex-col">
                <form class="flex flex-col lg:gap-2 lg:p-2 lg:px-4 rounded">
                    <div id="paragraph" class="hidden"></div>
                    <div class="flex flex-col lg:gap-2">
                        <label for="username">Identifiant login* :</label>
                        <input type="text" name="username" id="username"
                            class="p-2 border-[1px] border-white bg-[#eee] rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-300"
                            placeholder="Addresse électronique ou nom d'utilisateur" required>
                    </div>
                    <div class="flex flex-col lg:gap-2">
                        <label for="password">Mot de passe* :</label>
                        <input type="password" name="password" id="password"
                            class="p-2 border-[1px] border-white bg-[#eee] rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-300"
                            placeholder="Votre mot de passe">
                    </div>
                    <div class="flex lg:justify-end lg:p-2">
                        <button
                            class="validate bg-green-600 border-white border-[1px] lg:p-2 text-white rounded hover:border-green hover:bg-[#eee] hover:text-black cursor-pointer"
                            type="submit">Connexion</button>
                    </div>
                    <div class="flex lg:justify-between">
                        <a href="/home/forget" class="hover:underline hover:underline-offset-1">Mot de passe oublié
                            ?</a>
                        <a href="/home/index" class="hover:underline hover:underline-offset-1">Inscription</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="/assets/js/login.js"></script>
</body>

</html>