<?php
@session_start();
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/assets/css/output.css">
    <script src="/assets/js/tailwind.js"></script>
    <title>DM | Connexion</title>
</head>

<body>
    <div class="lg:max-w-[50%] lg:mt-[200px] lg:h-[500px] m-auto shadow-2xl flex lg:justify-between bg-[url('/assets/stories/six.jpg')] bg-no-repeat bg-cover rounded">
        <div class="lg:basis-[50%] flex justify-center items-center text-white">
            DM
        </div>
        <div
            class="lg:basis-[50%] bg-gray-200 lg:rounded-l-full lg:border-t-[1px] lg:border-b-[1px] lg:border-[#eee]">
            <div class="lg:mt-[90px] lg:mr-[10px] lg:max-w-[70%] m-auto p-1 flex flex-col">
                <form class="flex flex-col lg:gap-4 lg:p-2 lg:px-4 rounded lg:text-[14px]">
                    <div id="paragraph" class="mt-[-20px] hidden"></div>
                    <div class="flex flex-col lg:gap-2">
                        <label for="username" class="font-bold text-red-500">Identifiant login* :</label>
                        <input type="text" name="username" id="username"
                            class="p-2 border-[1px] border-black bg-gray-200 rounded focus:outline-none focus:ring-1 focus:ring-blue-300"
                            placeholder="Addresse électronique ou nom d'utilisateur" required>
                    </div>
                    <div class="flex flex-col lg:gap-2">
                        <label for="password" class="font-bold text-red-500">Mot de passe* :</label>
                        <input type="password" name="password" id="password"
                            class="p-2 border-[1px] border-black bg-gray-200 rounded focus:outline-none focus:ring-1 focus:ring-blue-300"
                            placeholder="Votre mot de passe">
                    </div>
                    <div class="flex lg:justify-end lg:p-2">
                        <button
                            class="lg:basis-[50%] validate bg-blue-600 border-white lg:border-[1px] lg:py-3 lg:px-1.5 text-white rounded hover:bg-blue-700 cursor-pointer ease-in duration-300"
                            type="submit">Connexion</button>
                    </div>
                    <div class="flex lg:justify-between">
                        <a href="/home/forget" class="hover:underline hover:underline-offset-1 hover:text-blue-600">Mot de passe oublié
                            ?</a>
                        <a href="/home/index" class="hover:underline hover:underline-offset-1">Inscription</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="/assets/js/login.js"></script>
</body>

</html>