<?php
    @session_start();
    $title = "Espace";
?>
    <?php require("../App/Views/Users/Components/Navbar/header.phtml"); ?>
    <main class="basis-[74%]">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore nihil repudiandae exercitationem facere vero, iure ipsum blanditiis delectus, eos ut, animi veritatis vel hic dolorum minus et voluptas dolor dolorem asperiores sit error nam libero amet deserunt! Dignissimos pariatur laudantium impedit in porro, neque earum vel, accusamus, perferendis necessitatibus quae quisquam. Tempore aliquid veritatis commodi vel quos ad neque, facere rem perspiciatis rerum provident porro distinctio, earum molestias expedita, velit magnam. Aut laboriosam suscipit alias! Debitis nisi iusto necessitatibus non aut dolore minima ut earum, vero vitae consequuntur maxime aliquid magni id modi ex quidem neque quo consectetur, nihil voluptate.
    </main>
    <script src="/assets/js/index.js"></script>
</body>
</html>

