<?php
@session_start();
$title = "Stories";
$x = "msg";
?>
<?php require("../App/Views/Users/Components/Navbar/header.phtml"); ?>
<main class="lg:basis-[83%] p-2 lg:h-screen relative">
    <div>Top</div>
    <div>Milieu</div>
    <div class="absolute bottom-[3%] w-[70%] left-[10%] flex justify-center">
        <div class="w-[70%] mx-auto" style="">
            <form action="#">
                <div class="border-black border-[1px] rounded-full flex justify-between items-center lg:p-2">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="gray" class="w-8 h-8">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M15.182 15.182a4.5 4.5 0 01-6.364 0M21 12a9 9 0 11-18 0 9 9 0 0118 0zM9.75 9.75c0 .414-.168.75-.375.75S9 10.164 9 9.75 9.168 9 9.375 9s.375.336.375.75zm-.375 0h.008v.015h-.008V9.75zm5.625 0c0 .414-.168.75-.375.75s-.375-.336-.375-.75.168-.75.375-.75.375.336.375.75zm-.375 0h.008v.015h-.008V9.75z" />
                    </svg>
                    <textarea cols="30" rows="1" class="resize-none basis-[90%] outline-none" placeholder="Tapez un message..."></textarea>
                </div>
            </form>
        </div>
    </div>
</main>
<script src="/assets/js/index.js"></script>
</body>

</html>