<?php
@session_start();
$title = "Stories";
$x = "stories";
?>
<?php require("../App/Views/Users/Components/Navbar/header.phtml"); ?>
<main class="lg:basis-[83%] p-2 lg:h-screen">
    <div class="lg:p-2 flex lg:gap-2 lg:items-center">
        <div class="lg:w-[200px] element rounded-lg relative cursor-pointer">
            <img src="/assets/users_pictures/<?= $_SESSION["image"] ?>" class="lg:h-[220px] rounded-lg" alt="livre">
            <h2 class="absolute bottom-0 left-0 text-white lg:p-1">Ajouter une story
                <?= $_SESSION["username"] ?>
            </h2>
            <div
                class="thanSvg rounded-lg absolute top-0 left-0 right-0 text-white lg:p-1 flex justify-center items-center h-[220px] bg-black opacity-60">
                <svg xmlns="http://www.w3.org/2000/svg" id="clickThan" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                    stroke="currentColor" class="w-12 h-12">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                </svg>
            </div>
        </div>
    </div>
</main>
<script src="/assets/js/index.js"></script>
</body>

</html>